apiVersion: v1
kind: Service
metadata:
  name: codigo-api
  namespace: codigo
  labels:
    app: codigo-api
spec:
  selector:
    app: codigo-api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.apiPort }}
    - name: metrics
      port: 8080
      targetPort: {{ .Values.service.apiPort }}
