apiVersion: v1
kind: Service
metadata:
  name: codigo-api
  namespace: codigo
  labels:
    app: codigo-api
spec:
  selector:
    app: codigo-api
  ports:
    - port: 80
      targetPort: {{ .Values.service.apiPort }}
