apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: codigo-api
  namespace: codigo
  labels:
    app: codigo-api
spec:
  selector:
    matchLabels:
      app: codigo-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

