apiVersion: v1
kind: Service
metadata:
  name: codigo-worker
  namespace: codigo
  labels:
    app: codigo-worker
spec:
  selector:
    app: codigo-worker
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080

